DATASET:
  INPUT_DIR: "test"
  INPUT_IMG_LIST: ["campus_001.jpg", "campus_002.jpg", "campus_003.jpg", "campus_004.jpg"]
  OUTPUT_DIR: "results"

FEATURES:
  FEATURE_DESCRIPTORS: "SIFT" #['SIFT', 'SURF',  ORB]
  FEATURE_MATCHING: (Brute_Force, NORM_L2) #(Brute_Force, NORM_HAMMING)
  FEATURE_MATCHING_THRESHOLD: 0.75

BLENDING: True
